### ISSUE TITLE
Dcoumentation 

### ISSUE THREAD

**Issue by LukaP-BB** [mparker2/g4predict#1]
Hi, is there a documentation for the output ? I can't find any information on how to interpret the columns of the bed.

**Comment by mparker2** [comment]
Hi @LukaP-BB 

There isn't any documentation I'm afraid and to be honest I haven't used the code in so long that my memory of what the output is is pretty vague. Someone emailed me a few years ago to ask the same question and this is what I told them:

> I haven't used or worked on that code since I finished my PhD and I don't remember what kind of state I left it in so I can't guarantee there are no bugs!
>
> IIRC there are two commands "intra" and "inter". "Intra" uses the quadparser method and so you get predictions with four runs of Gs. You can set the loop length and add bulges to some of the runs as well. The bed12 output has extra columns that show where the G-runs and loops are. If you load the output into IGV or another similar genome browser you should be able to the G-runs as thick blocks and the loops as thin connecting lines. Its standard bed12 which is used for exons and introns in gene models. Should be more information on the UCSC website: https://genome.ucsc.edu/FAQ/FAQformat.html#format1
>
> The name column for intra I think should have the format XtYbA,B,Cl where X is the number of tetrads (i.e. length of G-runs), Y is something to do with the position of bulges, and A,B,C is the length of the loops (I think in a 5' to 3' direction). For inter the name column is PG4_Xt_N where X is the number of tetrads and N is the number of G-runs. The idea for inter was to predict partial G4s and see if there were interactions with RNA or other DNA partial G4s. You probably want to run in intra mode I think.

I don't work on this anymore so I probably won't be able to help much more than that, sorry!

Best wishes
Matt

**Comment by LukaP-BB** [comment]
Thank you for your quick answer, we will see what we can do with this
